title: QuantumBasel Documentation
description: QuantumBasel HPTC Platform for Quantum Computing and AI Documentation
theme: just-the-docs

url: https://qb-documentation.github.io/qb-documentation

aux_links:
  Template Repository: https://github.com/donya-hardan/qb-documentation

plugins:
  - jekyll-default-layout

favicon_ico: "images/favicon.ico"
logo: "images/QB_Logo_2022_RGB.png"
color_scheme: light
