title: QuantumBasel Documentation
description: QuantumBasel HPTC Platform for Quantum Computing and AI Documentation
theme: just-the-docs

url: https://qb-documentation.github.io/qb-documentation

aux_links:
  Template Repository: https://github.com/donya-hardan/qb-documentation

plugins:
  - jekyll-default-layout

favicon: "images/favicon.ico"
logo: "images/QB_Logo_Positiv_NoSub_RGB.jpf"
color_scheme: light
